### ISSUE TITLE
Login screen auto-switch

### ISSUE THREAD

**Issue by dvogt23** [ohueter/autokbisw#13]
Hey thanks for that great piece of software 👍🏾 is that somehomw possible to make it switch as well for login-screen?

**Comment by ohueter** [comment]
Hi @dvogt23, I'm afraid that's not possible at the moment. There seem to be some technical obstacles as well, if one wanted to implement this as a new feature: https://github.com/jeantil/autokbisw/issues/16

**Comment by dvogt23** [comment]
Great, thanks. Closed.
