### ISSUE TITLE
Brew throws privilege error if I try to install as root user

### ISSUE THREAD

**Issue by vitto** [ohueter/autokbisw#14]
Due to the privileges required, I'm trying to install [autokbisw](https://github.com/ohueter/autokbisw) but I'm getting privileges errors:

<img width="870" alt="Screenshot 2022-11-09 alle 15 58 29" src="https://user-images.githubusercontent.com/461484/200864342-51c34a97-b8bc-487d-bbfb-9e8e2525784e.png">

Does exists some workaround to install it anyway?

**Comment by ohueter** [comment]
Installing as root is not required or advised, autokbisw needs to run with your user's rights. You need to resolve the Homebrew issues using the `chown` command (see your screenshot) and install without `sudo`.

**Comment by ohueter** [comment]
@vitte Were you able to resolve the issue? If not, feel free to reopen this ticket!
