### ISSUE TITLE
[Request] Edit modifier keys too

### ISSUE THREAD

**Issue by ItsPops** [ohueter/autokbisw#15]
Hello, this isn't an issue but a function request. 
Would it be possible to switch modifier keys (e.g: Ctrl is mapped to CMD, CMD is mapped to Ctrl) when switching keyboard layout ?
This way the internal keyboard would have the original settings but any external Windows keyboard would have Windows modifier keys working on iOS. 
Thanks !

**Comment by ohueter** [comment]
Hi @ItsPops, thanks for your request, but I think it's out of scope for this project. However, it seems that using [Ukulele](https://software.sil.org/ukelele/) to create a custom keyboard layout having swapped Cmd and Ctrl keys, and using autokbisw to switch between regular and custom layout might get you where you want. Hope that helps!

**Comment by ItsPops** [comment]
Thanks for your reply tho.
