### ISSUE TITLE
Any plans for Ventura?

### ISSUE THREAD

**Issue by retteghy** [ohueter/autokbisw#22]
I only noticed earlier OS versions among the releases. Do you plan to compile a version for Ventura?

**Comment by ohueter** [comment]
Seems like Ventura runners are available from Github (albeit labelled as Beta, https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), so should be a simple addition. Thanks for asking!
