### ISSUE TITLE
Automatic switching not working with a Bluetooth keyboard

### ISSUE THREAD

**Issue by 8bitmd** [ohueter/autokbisw#26]
I'm using a Logitech G915 TKL, AZERTY FR-PC layout. My Mac is also AZERTY but FR (no PC) layout.
Switching between keyboards doesn't change the input source. Tried the troubleshooting steps, reinstalling and re-applying permissions multiple times.

Any help is much appreciated!
Thank you.

**Comment by ohueter** [comment]
Hi @8bitmd, please try to run autokbisw directly in the Terminal with the `-v 2` flag. It should print a line for every pressed key. Try both keyboards and see if they are recognized as keyboards with different identifiers. If this works, it's likely a permissions issue.

If your Logitech keyboard is recognized as a mouse, there's no easy fix unfortunately (see the other open issues).
