### ISSUE TITLE
Unclear whether the tool doesn't run on Sonoma, or I'm doing something wrong.

### ISSUE THREAD

**Issue by NiccoloGranieri** [ohueter/autokbisw#27]
Hi,

installed the tool without any issues, gave it all the permissions it needed, but I struggle to follow the usage instructions.

If I type with my MacBook's inbuilt keyboard, and set the input source from the menu icon, this doesn't seem to affect the UserDefaults values. Am I doing something wrong? Does the "Usage Instructions" section need to be followed in a particular way?

P.S. I'm using an MX Keys, and I'm aware there are some issues with that, but already the ability to autoswitch when I'm using the inbuilt keyboard would be great for my use.

Thanks!

**Comment by ohueter** [comment]
You could try the following procedure (adapted from yours, to be sure start autokbisw from the command line again and monitor the verbose output like you did before):

Opened textedit
typed random stuff on the inbuilt keyboard
switched the input language to italian
(new) typed random stuff on the inbuilt keyboard
typed random stuff on secondary keyboard
switched the language to English
(new) typed random stuff on secondary keyboard

That should absolutely work from my unterstanding. 

If it doesn't (please paste the output from the command line here, a single keystroke is enough for switching keyboards), it may be a permissions issue. Did you try the following?

> Re-grant the required privileges to the service by removing and re-adding the executable under System Preferences > Security & Privacy > Privacy > Input Monitoring. The path to add should either be /usr/local/bin/autokbisw (on Intel Macs) or /opt/homebrew/opt/autokbisw/bin/autokbisw (on Apple M1 Macs).

**Comment by NiccoloGranieri** [comment]
Hi @ohueter, I have followed the guide you provided (both for setup and for re-assigning permissions) and neither worked.

However, when I went to the command line to paste the output for you to look at, it exhibited a behaviour it never exhibited before.

As soon as I launch autobfsw with verbosity 2, the first keystroke I press on my inbuilt keyboard changes the input source to GB. From that moment on, no other keystroke changes it, not even if I manually revert it to Italian.

However, this behaviour is reproducible, because if I "exit" verbose mode, and I re-enter it, the first keystroke on my inbuilt keyboard will retriever the input source to GB.

```autokbisw -v 2

Starting with useLocation: false - verbosity: 2
received event from keyboard MX Keys-[1133-45915-Logitech-5F82F70C668EE4A6] - 1833265849 - 4295029378
ignoring event as device is a mouse
received event from keyboard MX Keys-[1133-45915-Logitech-5F82F70C668EE4A6] - 1833265849 - 4295029378
ignoring event as device is a mouse
received event from keyboard MX Keys-[1133-45915-Logitech-5F82F70C668EE4A6] - 1833265849 - 4295029378
ignoring event as device is a mouse
received event from keyboard MX Keys-[1133-45915-Logitech-5F82F70C668EE4A6] - 1833265849 - 4295029378
ignoring event as device is a mouse
hreceived event from keyboard Apple Internal Keyboard / Trackpad-[1452-835-Apple Inc.-FM7231300VENX0QAN+EBT] - 51 - 4294969886
set input source to <TSMInputSource 0x600003b7b480> KB Layout: British (id=2) for keyboard Apple Internal Keyboard / Trackpad-[1452-835-Apple Inc.-FM7231300VENX0QAN+EBT]
received event from keyboard Apple Internal Keyboard / Trackpad-[1452-835-Apple Inc.-FM7231300VENX0QAN+EBT] - 51 - 4294969886
received event from keyboard Apple Internal Keyboard / Trackpad-[1452-835-Apple Inc.-FM7231300VENX0QAN+EBT] - 51 - 4294969886
received event from keyboard Apple Internal Keyboard / Trackpad-[1452-835-Apple Inc.-FM7231300VENX0QAN+EBT] - 51 - 4294969886
received event from keyboard Apple Internal Keyboard / Trackpad-[1452-835-Apple Inc.-FM7231300VENX0QAN+EBT] - 51 - 4294969886
received event from keyboard Apple Internal Keyboard / Trackpad-[1452-835-Apple Inc.-FM7231300VENX0QAN+EBT] - 51 - 4294969886
received event from keyboard Apple Internal Keyboard / Trackpad-[1452-835-Apple Inc.-FM7231300VENX0QAN+EBT] - 51 - 4294969886
received event from keyboard Apple Internal Keyboard / Trackpad-[1452-835-Apple Inc.-FM7231300VENX0QAN+EBT] - 51 - 4294969886
received event from keyboard MX Keys-[1133-45915-Logitech-5F82F70C668EE4A6] - 1833265849 - 4295029378
ignoring event as device is a mouse
dreceived event from keyboard MX Keys-[1133-45915-Logitech-5F82F70C668EE4A6] - 1833265849 - 4295029378
ignoring event as device is a mouse
received event from keyboard MX Keys-[1133-45915-Logitech-5F82F70C668EE4A6] - 1833265849 - 4295029378
ignoring event as device is a mouse
received event from keyboard MX Keys-[1133-45915-Logitech-5F82F70C668EE4A6] - 1833265849 - 4295029378
ignoring event as device is a mouse
received event from keyboard MX Keys-[1133-45915-Logitech-5F82F70C668EE4A6] - 1833265849 - 4295029378
ignoring event as device is a mouse
received event from keyboard MX Keys-[1133-45915-Logitech-5F82F70C668EE4A6] - 1833265849 - 4295029378
ignoring event as device is a mouse
received event from keyboard MX Keys-[1133-45915-Logitech-5F82F70C668EE4A6] - 1833265849 - 4295029378
ignoring event as device is a mouse
received event from keyboard MX Keys-[1133-45915-Logitech-5F82F70C668EE4A6] - 1833265849 - 4295029378
ignoring event as device is a mouse

```

**Comment by ohueter** [comment]
Hi Niccolo,

I'm sorry but it seems like you're affected from the MX keyboard issue. autokbisw has saved the GB layout for your internal keyboard and sets (restores) it when you start typing on it. It doesn't change when you start typing on your external keyboard because it is ignored due to the MX issue. 

Unfortunately there's no easy workaround at the moment. If you're a little bit familiar with coding, you could remove the MX check from the source, compile the binary and use that version.

**Comment by NiccoloGranieri** [comment]
Hi @ohueter, thanks for the tip. I can confirm the system works with non logitech keyboards.

However, I cloned and built the version on branch 1.5, and it now works also on my Logitech wireless keyboard! Can I ask why we're not merging with main? Or at least creating an "untested" standalone for those with Logitech keyboards?

Thanks!

**Comment by ohueter** [comment]
Happy you found a way to get autokbisw working for your setup! 🥳

Ignoring MX input devices is an intentional feature to solve a problem some users had with autokbisw. Changing it back would solve the problems of a different group of users, but re-introduce the problem the first user group had. The way to solve these issues for all users is layed out in the open issues tagged `need help`, please feel free to contribute!

Verbosity mode has no influence on the functionality of the program. I would assume that in your case it rather hints at persisting permissions issues with the service that Homebrew installed. You should make sure you're only running only one instance of the program with correct permissions for that exact executable. macOS hides the program path in System Settings, but this does make a difference. Maybe thats what causing this problem for you?

**Comment by NiccoloGranieri** [comment]
It absolutely is @ohueter, thanks for the reply.

I am now struggling to get the executable added to the background task. This happened automagically with `brew service start autokbisw` as it triggered all the privacy bells and whistles, and added the service to the background tasks.

If I launch the executable from terminal, I need to keep the terminal open for it to run, and it doesn't get added to the background tasks. Any documentation on that?

**Comment by ohueter** [comment]
The service definition as plist should look something like that:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>autokbisw</string>
    <key>ProgramArguments</key>
    <array>
      <string>/path/to/autokbisw</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
  </dict>
</plist>
```

but I totally forgot how to add that to sysctl. You need to find out by yourself I'm sorry.

**Comment by tim-hilt** [comment]
I don't know if this was said before, but for me the problem was, that I had Karabiner running, which proxies keyboard-input (as far as I understand), so the kernel sees input from the same keyboard, no matter the physical keyboard that is being used.
