### ISSUE TITLE
Autobisw not installing

### ISSUE THREAD

**Issue by creativerat** [ohueter/autokbisw#28]
Some info on the setup. I recently upgraded to Ventura so that I can actually use this. I do have Xcode installed and even cloned using the URL into Xcode. I do have Homebrew installed.

I keep entering the Installation code into Terminal but it just won't install this is what it spits out:

==> swift build -c release --disable-sandbox
Last 15 lines from /Users/*Censoring for Privacy*/Library/Logs/Homebrew/autokbisw/01.swift:
2023-10-16 15:58:31 +0000

swift
build
-c
release
--disable-sandbox

error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'

What might I be doing wrong? And please note I'm a dumbass normie, I have little to 0 coding understanding.

**Comment by ohueter** [comment]
Could you run 
```
xcode-select --print-path
```
in the terminal and post the output? It should be `/Applications/Xcode.app/Contents/Developer`. If it's not, could see if running `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer` fixes the compilation?

**Comment by max-g** [comment]
Had the error described in this issue. 

```
xcode-select --print-path

outputs: /Library/Developer/CommandLineTools
```

After running `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer` and re-running `brew install ohueter/tap/autokbisw` it build and installed correctly.
