### ISSUE TITLE
Likely a dumb question

### ISSUE THREAD

**Issue by eduardosalata** [ohueter/autokbisw#30]
How do I make it start with the system, and run without having the terminal tab open

**Comment by ohueter** [comment]
Installation via Homebrew does this for you, please see here: https://github.com/ohueter/autokbisw#installation

Without using Homebrew, you could add autokbisw as a Launch Daemon for your user. You can find an example .plist file here: https://github.com/ohueter/autokbisw/issues/27#issuecomment-1768167959
and documentation by searching the web for "macos plist service" or official docs by Apple here: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html

However, I can't help you with that.
