### ISSUE TITLE
CPU intensive?

### ISSUE THREAD

**Issue by Emilostuff** [ohueter/autokbisw#31]
I really love the plugin, but on my machine (Macbook Pro "15 M1) I observe it using up to 45% of the CPU in spikes once or twice every second - on average causing a few percent higher CPU load than without the plugin running. Could this a bug or does it really need this many resources to work properly?

**Comment by ohueter** [comment]
Hi Emil, on my machine it sits at 0% most of the time, rising to 1-2% occasionally (just by looking at activity monitor stats). autokbisw essentially only listens to keyboard events and does a system call if needed, hardly any CPU required. Could you share how you measured 45%? And sorry but: have you tried turning your mac off and on again? ;-)
