### ISSUE TITLE
Bug if "Automatically switch to a document's input source" is toggled ON in system keyboard settings

### ISSUE THREAD

**Issue by PrinceEntree8** [ohueter/autokbisw#33]
As per title, the second setting is turned on, the application might not work as expected.
<img width="827" alt="image" src="https://github.com/ohueter/autokbisw/assets/32601364/07fa253b-4f8a-49ae-94ad-f01b0f2a509a">

Bug fix suggestion: Add in the Readme or QA section, the fix.

**Comment by ohueter** [comment]
Hi @PrinceEntree8, thanks for reporting. I can see this might lead to unexpected behaviour. I'm adding a FAQ section to the README and want to include this, could you briefly describe what (bug-like) behaviour you are observing?
