### ISSUE TITLE
Apple Wallet issue

### ISSUE THREAD

**Issue by marvinjoa** [ohueter/autokbisw#40]
Hey,

I'm wondering if anybody has an issue with autokbisw and Apple Wallet on the Sequoia Developer beta.
I've had this on the regular macOS versions before as well, but was able to fix it permanently previously.
Apple Wallet keeps disabling itself with the message:

> Apple Pay on your Mac is disabled because security settings were modified.

I've run all troubleshooting I could find and some of it would work until a reboot. 
Now I'm trying to figure out which app is causing this and the only app I can think of is autokbisw, because it is basically very similar to a key logger.

**Comment by marvinjoa** [comment]
Just to add to this:

Could this be, because I didn't compile it on the fresh install, but dragged the Time Machine backup of it to it's place?

**Comment by ohueter** [comment]
Thank you for reporting! Could you check if enabling / disabling autokbisw under `System Preferences > Security & Privacy > Privacy > Input Monitoring` reproducibly resolves your issues with Wallet?

**Comment by marvinjoa** [comment]
> Thank you for reporting! Could you check if enabling / disabling autokbisw under `System Preferences > Security & Privacy > Privacy > Input Monitoring` reproducibly resolves your issues with Wallet?

After running troubleshooting again (trying to add cards to another user account and denying the Wallet reset, since it was set up with another user), Wallet on my account became available again with the Input Monitoring disabled.

As soon as I have a little time, I'm going to install Xcode and recompile it on my current installation to see if it makes any change, because as of now the tool was compiled on a previous installation.
But it is definitely caused by autokbisw.

**Comment by marvinjoa** [comment]
Update:

Building the binary by myself via Homebrew gave me the same issue again.

**Comment by ohueter** [comment]
Thanks again for trying to debug the situation. Googling the initial message turns up a lot of weird fixes and solutions. It seems like it's hard to tell if what you're observing is the root cause or just a symptom of an erroneous system state. I guess we have to wait until more people report on this issue after the official Sequoia release, and if that happens, find some official documentation on what exactly is causing the interference.

**Comment by marvinjoa** [comment]
With autokbisw uninstalled or the input monitoring disabled, Apple Pay starts working permanently again after going to another user account and trying to add a card there (this is one of the troubleshooting suggestions, to reset the error message on the main account). 
It even works when autokbisw is running, but only until the next reboot or login.

I think Apple might be getting stricter with the privacy features / APIs overall. In previous beta builds it asks every week if one is still okay with screen recoding enabled for apps that had it enabled. (https://9to5mac.com/2024/08/14/macos-sequoia-screen-recording-prompt-monthly/)
I hope this is a bug rather than a feature, but the beta is coming to an end.

I could report a bug via feedback assistant to Apple.

**Comment by marvinjoa** [comment]
Just reported this behavior to Apple via Feedback Assistant.
If someone is running into the same issue, here's my Feedback ID for reference: FB15022927
![Screenshot 2024-09-03 at 4 33 04 PM](https://github.com/user-attachments/assets/656e11ed-71dc-497a-9bb2-4aa41910171c)
