### ISSUE TITLE
autokbisw does not recognize MacBooks internal keyboard anymore

### ISSUE THREAD

**Issue by leojue** [ohueter/autokbisw#42]
I have used autokbisw for months now without any major problems. But today I realized that something with the layout switching is wrong. I use autokbisw to change between my MacBooks internal keyboard and my external keyboard with different keyboard layouts. After investigating the issue I noticed the following problem(s):

1. The devices are not recognized correctly anymore. `autokbisw list` gives me my external keyboard (2 times, because sometimes it's connected via Bluetooth and sometimes via USB) and my Logitech mouse. The internal keyboard of the MacBook however is not getting recognized at all. When I checked the last time a few weeks ago, the internal keyboard was correctly being recognized and the mouse was correctly not being recognized.
2. The program behaves "weirdly" at times. Deactivating the mouse at one time only worked for a few seconds. This also messed up the layout switching. But at the moment, this problem luckily seems to be gone.

After I noticed the problems I tried updating the program, re-started the service and re-granted the required privileges.
A few days ago I got a new keyboard. Prior to that I only used an external keyboard with a wired connection, so maybe that made me notice the problem? But that does not make too much sense, because everything worked fine in the first days.

Any help with my problem would be very much appreciated! I really do like the program and would love to be able to continue using it🙂

Thanks in advance!

**Comment by ohueter** [comment]
Thanks for your detailed bug report! I can reproduce the issue und will look into it as soon as possible. It seems like in the new version 2.0, new devices are not recognized in all cases.

Maybe this workaround can help in the meantime.

Stop the service:
```brew services stop ohueter/tap/autokbisw```

Interact with the existing devices using the `list`, `enable` and `disable` commands (e.g., disable your mouse).

Start the service again:
```brew services start ohueter/tap/autokbisw```

Alternatively, you can download and use the latest working release from https://github.com/ohueter/autokbisw/releases/tag/1.4.4 and start autokbisw directly.

**Comment by ohueter** [comment]
Hi @leojue, please try upgrading to version 2.0.1 und see if the fixes resolve your issues: `brew upgrade ohueter/tap/autokbisw`

Thanks for beta-testing! 😄

Edit: My machine required re-granting permissions & a full restart to get automatic switching working again after the upgrade. Maybe you should run `autokbisw clear` as well to remove all settings, as they may be in an invalid state.

**Comment by leojue** [comment]
Yes, the new version fixes my issues! Now everything works as expected. Thank you very much @ohueter for your quick reply and solution for the problem😃 

Have a nice day!

**Comment by ohueter** [comment]
Glad that it works again! Happy holidays!
